In [1]:
import pandas as pd
import requests

In [41]:
response = requests.get("https://api.artic.edu/api/v1/artworks/search?&&page=1")

In [40]:
pd.DataFrame(response.json()['data'])[['_score','id','api_model','title','thumbnail']]

,_score,id,api_model,title,thumbnail
0,8.016705,16629,artworks,Fruits of the Midi,"{'lqip': 'data:image/gif;base64,R0lGODlhBgAFAP..."
1,8.012708,125774,artworks,Mother-and-Child Figure (Bwanga bwa Chibola),"{'lqip': 'data:image/gif;base64,R0lGODlhAwAFAP..."
2,8.011989,7733,artworks,Peasants Going to Work,"{'lqip': 'data:image/gif;base64,R0lGODlhBAAFAP..."
3,8.009827,3446,artworks,The Birth of Annette,"{'lqip': 'data:image/gif;base64,R0lGODlhBwAFAP..."
4,8.008899,2581,artworks,Venus and Adonis (?) with the Duck Hunt,"{'lqip': 'data:image/gif;base64,R0lGODlhBAAFAP..."
5,8.007763,5580,artworks,Horse,"{'lqip': 'data:image/gif;base64,R0lGODlhBAAFAP..."
6,8.004866,19386,artworks,Susano-o no Mikoto Killing the Eight-headed Dr...,"{'lqip': 'data:image/gif;base64,R0lGODlhAgAFAP..."
7,8.004451,87008,artworks,"Shower Below the Summit (Sanka hakuu), from th...","{'lqip': 'data:image/gif;base64,R0lGODlhBwAFAP..."
8,8.004140,7604,artworks,The Little Errand Girl,"{'lqip': 'data:image/gif;base64,R0lGODlhBAAFAP..."
9,8.003725,133859,artworks,Lady Reading the Letters of Heloise and Abelard,"{'lqip': 'data:image/gif;base64,R0lGODlhBAAFAP..."

In [46]:
df = pd.DataFrame()

IndentationError: unexpected indent (4029466700.py, line 2)

In [43]:
df

Empty DataFrame
Columns: []
Index: []

In [51]:
for i in range(1,101):
    response = requests.get(f'https://api.artic.edu/api/v1/artworks/search?page={i}')
    
    temp_df = pd.DataFrame(response.json()['data'])[
        ['_score','id','api_model','title','thumbnail']
    ]
    
    df = pd.concat([df, temp_df], ignore_index=True)

In [52]:
df

,_score,id,api_model,title,thumbnail
0,7.073046e+06,129884,artworks,Starry Night and the Astronauts,"{'lqip': 'data:image/gif;base64,R0lGODlhBAAFAP..."
1,3.536523e+06,28560,artworks,The Bedroom,"{'lqip': 'data:image/gif;base64,R0lGODlhBgAFAP..."
2,2.357682e+06,21023,artworks,Buddha Shakyamuni Seated in Meditation (Dhyana...,"{'lqip': 'data:image/gif;base64,R0lGODlhBAAFAP..."
3,1.768262e+06,137125,artworks,Many Mansions,"{'lqip': 'data:image/gif;base64,R0lGODlhBgAFAP..."
4,7.073046e+05,229393,artworks,Untitled,"{'lqip': 'data:image/gif;base64,R0lGODlhBAAFAP..."
...,...,...,...,...,...
995,8.007763e+00,5580,artworks,Horse,"{'lqip': 'data:image/gif;base64,R0lGODlhBAAFAP..."
996,8.004866e+00,19386,artworks,Susano-o no Mikoto Killing the Eight-headed Dr...,"{'lqip': 'data:image/gif;base64,R0lGODlhAgAFAP..."
997,8.004451e+00,87008,artworks,"Shower Below the Summit (Sanka hakuu), from th...","{'lqip': 'data:image/gif;base64,R0lGODlhBwAFAP..."
998,8.004140e+00,7604,artworks,The Little Errand Girl,"{'lqip': 'data:image/gif;base64,R0lGODlhBAAFAP..."
999,8.003725e+00,133859,artworks,Lady Reading the Letters of Heloise and Abelard,"{'lqip': 'data:image/gif;base64,R0lGODlhBAAFAP..."

In [53]:
df.shape

(1000, 5)

In [54]:
df.to_csv('artworks.csv')

In [68]:
response2=requests.get("https://internships-api.p.rapidapi.com/active-jb-7d")

In [69]:
pd.DataFrame(response2.json())

ValueError: If using all scalar values, you must pass an index