In [1]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [4]:
df = pd.read_csv('train.csv')[['Age','Fare','SibSp','Parch','Survived']]

In [5]:
df.dropna(inplace = True)

In [6]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [7]:
df['Family'] = df['Parch']+df['SibSp']

In [18]:
df.sample(6)

      Age      Fare  SibSp  Parch  Survived  Family
676  24.5    8.0500      0      0         0       0
746  16.0   20.2500      1      1         0       2
553  22.0    7.2250      0      0         1       0
258  35.0  512.3292      0      0         1       0
761  41.0    7.1250      0      0         0       0
369  24.0   69.3000      0      0         1       0

In [19]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
X_train.head()

      Age     Fare  SibSp  Parch  Family
328  31.0  20.5250      1      1       2
73   26.0  14.4542      1      0       1
253  30.0  16.1000      1      0       1
719  33.0   7.7750      0      0       0
666  25.0  13.0000      0      0       0

In [22]:
#without binarization

clf = DecisionTreeClassifier()

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_test,y_pred)

0.6223776223776224

In [23]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

np.float64(0.6456964006259781)

In [24]:
# applying binarixation

from sklearn.preprocessing import Binarizer

In [28]:
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['Family'])
],remainder='passthrough')

In [29]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [34]:
pd.DataFrame(X_train_trf,columns=['Family','Age','Fare','',''])

     Family   Age      Fare
0       1.0  31.0   20.5250  1.0  1.0
1       1.0  26.0   14.4542  1.0  0.0
2       1.0  30.0   16.1000  1.0  0.0
3       0.0  33.0    7.7750  0.0  0.0
4       0.0  25.0   13.0000  0.0  0.0
..      ...   ...       ...  ...  ...
566     1.0  46.0   61.1750  1.0  0.0
567     0.0  25.0   13.0000  0.0  0.0
568     0.0  41.0  134.5000  0.0  0.0
569     1.0  33.0   20.5250  1.0  1.0
570     0.0  33.0    7.8958  0.0  0.0

[571 rows x 5 columns]

In [35]:
clf = DecisionTreeClassifier()
clf.fit(X_train_trf,y_train)
y_pred2 = clf.predict(X_test_trf)

accuracy_score(y_test,y_pred2)

0.6433566433566433

In [37]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=10,scoring='accuracy'))

np.float64(0.6415884194053207)